# Generated by Django 5.1 on 2024-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
