# Generated by Django 5.1 on 2024-09-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_labour_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
