# Generated by Django 5.1 on 2025-03-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='labour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='last_booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
