# Generated by Django 5.1 on 2025-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
