# Generated by Django 5.1 on 2025-03-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_waitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
